---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp-deployment
 labels:
  app: myapp
spec:
 replicas: 1
 selector:
  matchLabels:
   app: myapp
 template:
  metadata: 
   labels:
    app: myapp
  spec:
   containers:
   - name: myapp
     image: devopscicd.jfrog.io/default-docker-local/devops:tagversion
     ports:
     - containerPort: 8082
   imagePullSecrets:
     - name: devops  

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 60
    periodSeconds: 5
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 10
  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 60
    periodSeconds: 5
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 10
  resources:
    requests:
      memory: 0.25Gi
      cpu: 0.5
    limits:
      memory: 0.25Gi 
      cpu: 0.5
