---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp-deployment
 labels:
  app: myapp
spec:
 replicas: 1
 selector:
  matchLabels:
   app: myapp
 template:
  metadata: 
   labels:
    app: myapp
  spec:
   containers:
   - name: myapp
     image: anuj23/githubactions:$GITHUB_RUN_ID
     ports:
     - containerPort: 8082
   imagePullSecrets:
     - name: github  

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
