name: Java CI with Maven

on:
  pull_request:
    branches: [ main ]
    
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
        distribution: 'adopt'
        cache: maven
    - name: Grant execute permission for POM file
      run: chmod +x pom.xml    
    - name: Build with Maven
      run: mvn clean package --file pom.xml
#    - name: Run Test cases
#      run: mvn test --file pom.xml
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    - name: SonarQube Quality Gate check
      uses: sonarsource/sonarqube-quality-gate-action@master
      # Force to fail step after specific time
      timeout-minutes: 5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Install Datree
      run: curl https://get.datree.io | /bin/bash
        
    - name: Run Datree's policy check
      run: datree test kube.yaml
